name: Feature request(功能请求)
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: "注: 你可以使用中文来填写此issue。"

  - type: textarea
    attributes:
      label: What new features do you want(你想要什么新功能)?
      description: A clear and concise description of what of your requirements(请清晰而简明地描述你的需求).
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional context(额外说明)
      description: |
        Add any other context or screenshots about the feature request here(添加其它关于你的需求的说明或截图).
    validations:
      required: false

  - type: checkboxes
    id: know
    attributes:
      label: This issue is unique(这个issue是唯一的)
      options:
        - label: I have searched the issue tracker and did not find an issue describing my bug.
          required: true
